name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Build
        run: go build -o github-runner-prometheus-exporter cmd/exporter/main.go

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: github-runner-prometheus-exporter
